### PR TITLE
Add recommended git workflow to work mode doc

### PR DESCRIPTION
**Pull request by brentzundel**
Signed-off-by: Brent <brent.zundel@gmail.com>

### CODE REVIEW

**Comment by TallTed** [comment]
That's a whole lot more complex than it needs to be (and handwaves past some of the potentially challenging parts), especially for folks who aren't already accustomed to running a desktop/local git. GitHub makes it easy to edit online, automatically creating a personal fork, etc. For most contributors, who are likely to be making small changes to a single doc (not broad changes across a repo or even across a large doc), this will be sufficient. Even for large changes, this can be fine (as evidenced by my contributions, here and elsewhere).

**Comment by iherman** [comment]
> GitHub makes it easy to edit online, automatically creating a personal fork, etc. For most contributors, who are likely to be making small changes to a single doc (not broad changes across a repo or even across a large doc), this will be sufficient.

True. But what github does for such a case is not dissimilar to what @brentzundel described (altough I agree it is worth emphasizing). Indeed, unless you have a special right, github will fork the repository and create a pull request for you from that forked repo.

Maybe the only change is to emphasize that, if you only want to make small changes, you are not _required_ to clone your forked repo to your local machine, and many changes can be done with github's built-in editor directly on the fork.

**Comment by TallTed** [comment]
@iherman @brentzundel - My point is that these instructions are not detailed enough for a novice git user (who may be an experienced github user), while probably being more detailed than necessary for an experienced git user. (I am fairly tech-savvy and experienced with github, but I could not perform the steps listed by following these instructions without external assistance/guidance.)

**Comment by brentzundel** [comment]
I agree with Ted's assessment, but don't feel that our work mode page is the correct place for a complete git tutorial. 
In my imagination someone would read step one: "Create a fork of the repository under your own github account," and then figure out how to do that before moving on to the next step (perhaps by googling "how to create a fork of a repository under my github account").
If the added text does more harm than good, I am fine dropping it, but my hope was that it is complete enough to act as a guide for someone who is learning git.

**Comment by TallTed** [comment]
I would just say something like "Use GitHub or other `git`-based tools to produce and submit Pull Requests, or to open Issues, on the repository holding the document you want to be changed. Some users (usually Editors and/or Chairs, but sometimes including others) may have `git` permissions that allow them to directly apply changes, but best practice is to use PRs in most cases, in order to gather feedback and enable reversion if/when necessary."

Including link(s) to some `git`/GitHub guide(s)/tutorial(s) would be fine, but we should not reinvent those guides (which the current text of this PR starts to do).

**Comment by brentzundel** [comment]
@TallTed @iherman I have vastly simplified this PR and added some links to official tutorials that I feel express the original intent of this change.

**Review by iherman — APPROVED** [review]

**Pull request merged**
